## Week 1 Assignment
### GEFlores


### Re-create **ALL** the manipulations in lecture material Chapter 1

Import pandas library

In [2]:
import pandas as pd

Load data

In [3]:
df = pd.read_csv('data_wk1/gapminder.tsv', sep = '\t')

Read data (First 5 lines)

In [4]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Looking at first 8 lines

In [5]:
df.head(8)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945

What type is our variable, df?

In [6]:
type(df)

pandas.core.frame.DataFrame

What about a specific column's type?

In [8]:
type(df['year'])

pandas.core.series.Series

How many rows and columns in the data, or it's shape?

In [10]:
df.shape

(1704, 6)

What are the columns in our data?

In [11]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

Column types

In [12]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

Column Info

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

#### Selecting subsets of your data

Selecting a single column

In [14]:
country_df = df['country']
country_df.head(10)

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
5    Afghanistan
6    Afghanistan
7    Afghanistan
8    Afghanistan
9    Afghanistan
Name: country, dtype: object

In [15]:
country_df.tail(10)

1694    Zimbabwe
1695    Zimbabwe
1696    Zimbabwe
1697    Zimbabwe
1698    Zimbabwe
1699    Zimbabwe
1700    Zimbabwe
1701    Zimbabwe
1702    Zimbabwe
1703    Zimbabwe
Name: country, dtype: object

Selecting multiple columns

In [16]:
subset = df[['country', 'continent', 'year']]
subset.head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [17]:
subset.shape

(1704, 3)

Passing a list

In [18]:
sub_columns = ['country', 'continent', 'year']
sub_df = df[sub_columns]
sub_df.head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

The numbers in the table above are just row numbers, not tied to the data

Selecting by index lable vs selecting by row

In [19]:
# making a copy of our df
year_df = df.copy()

# creating an index lable
year_df.set_index('year', inplace=True)

In [ ]:
# looking at our data with an index label
year_df.head()

          country continent  lifeExp       pop   gdpPercap
year
1952  Afghanistan      Asia   28.801   8425333  779.445314
1957  Afghanistan      Asia   30.332   9240934  820.853030
1962  Afghanistan      Asia   31.997  10267083  853.100710
1967  Afghanistan      Asia   34.020  11537966  836.197138
1972  Afghanistan      Asia   36.088  13079460  739.981106

In [22]:
year_df.loc[1952].head(10)

          country continent  lifeExp       pop     gdpPercap
year
1952  Afghanistan      Asia   28.801   8425333    779.445314
1952      Albania    Europe   55.230   1282697   1601.056136
1952      Algeria    Africa   43.077   9279525   2449.008185
1952       Angola    Africa   30.015   4232095   3520.610273
1952    Argentina  Americas   62.485  17876956   5911.315053
1952    Australia   Oceania   69.120   8691212  10039.595640
1952      Austria    Europe   66.800   6927772   6137.076492
1952      Bahrain      Asia   50.939    120447   9867.084765
1952   Bangladesh      Asia   37.484  46886859    684.244172
1952      Belgium    Europe   68.000   8730405   8343.105127

In [23]:
year_df.iloc[0]

country      Afghanistan
continent           Asia
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 1952, dtype: object

Getting multiple rows

In [24]:
year_df.iloc[[0,10,100]]

          country continent  lifeExp       pop   gdpPercap
year
1952  Afghanistan      Asia   28.801   8425333  779.445314
2002  Afghanistan      Asia   42.129  25268405  726.734055
1972   Bangladesh      Asia   45.252  70759295  630.233627

In [27]:
index_range = list(range(0,10))

year_df.iloc[index_range]

          country continent  lifeExp       pop   gdpPercap
year
1952  Afghanistan      Asia   28.801   8425333  779.445314
1957  Afghanistan      Asia   30.332   9240934  820.853030
1962  Afghanistan      Asia   31.997  10267083  853.100710
1967  Afghanistan      Asia   34.020  11537966  836.197138
1972  Afghanistan      Asia   36.088  13079460  739.981106
1977  Afghanistan      Asia   38.438  14880372  786.113360
1982  Afghanistan      Asia   39.854  12881816  978.011439
1987  Afghanistan      Asia   40.822  13867957  852.395945
1992  Afghanistan      Asia   41.674  16317921  649.341395
1997  Afghanistan      Asia   41.763  22227415  635.341351

Getting a "slice" of data

In [28]:
index_range

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
index_range[0:5]

[0, 1, 2, 3, 4]

In [30]:
# All rows, columns year and pop
df.loc[:, ['year', 'pop']].head(10)

   year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460
5  1977  14880372
6  1982  12881816
7  1987  13867957
8  1992  16317921
9  1997  22227415

In [31]:
# All rows, first 3 columns
df.iloc[:, :3].head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

Filtering and aggragation

In [32]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

Breaking up long lines with \ at the end

In [33]:
df.groupby(['year', 'continent']) \
[['lifeExp', 'gdpPercap']]. \
mean().head(n=20)

                  lifeExp     gdpPercap
year continent
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650
1957 Africa     41.266346   1385.236062
     Americas   55.960280   4616.043733
     Asia       49.318544   5787.732940
     Europe     66.703067   6963.012816
     Oceania    70.295000  11598.522455
1962 Africa     43.319442   1598.078825
     Americas   58.398760   4901.541870
     Asia       51.563223   5729.369625
     Europe     68.539233   8365.486814
     Oceania    71.085000  12696.452430
1967 Africa     45.334538   2050.363801
     Americas   60.410920   5668.253496
     Asia       54.663640   5971.173374
     Europe     69.737600  10143.823757
     Oceania    71.310000  14495.021790

Flatten results

In [34]:
df.groupby(['year', 'continent']) \
[['lifeExp', 'gdpPercap']]. \
mean(). \
reset_index().\
head(15)

    year continent    lifeExp     gdpPercap
0   1952    Africa  39.135500   1252.572466
1   1952  Americas  53.279840   4079.062552
2   1952      Asia  46.314394   5195.484004
3   1952    Europe  64.408500   5661.057435
4   1952   Oceania  69.255000  10298.085650
5   1957    Africa  41.266346   1385.236062
6   1957  Americas  55.960280   4616.043733
7   1957      Asia  49.318544   5787.732940
8   1957    Europe  66.703067   6963.012816
9   1957   Oceania  70.295000  11598.522455
10  1962    Africa  43.319442   1598.078825
11  1962  Americas  58.398760   4901.541870
12  1962      Asia  51.563223   5729.369625
13  1962    Europe  68.539233   8365.486814
14  1962   Oceania  71.085000  12696.452430

Count unique

In [35]:
df.groupby('continent')['country'].nunique()

continent
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: country, dtype: int64

### Similar set of manipulations from UCI Machine Learning archive

Loaddata

In [10]:
import pandas as pd

df = pd.read_csv('UCI_Data/cirrhosis.csv')

Look at data

In [18]:
df.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0

Look at shape of our datframe

In [22]:
df.shape

(418, 20)

What do our columns look like?

In [26]:
df.columns

Index(['ID', 'N_Days', 'Status', 'Drug', 'Age', 'Sex', 'Ascites',
       'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin', 'Cholesterol',
       'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets',
       'Prothrombin', 'Stage'],
      dtype='object')

In [29]:
df.dtypes

ID                 int64
N_Days             int64
Status            object
Drug              object
Age                int64
Sex               object
Ascites           object
Hepatomegaly      object
Spiders           object
Edema             object
Bilirubin        float64
Cholesterol      float64
Albumin          float64
Copper           float64
Alk_Phos         float64
SGOT             float64
Tryglicerides    float64
Platelets        float64
Prothrombin      float64
Stage            float64
dtype: object

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             418 non-null    int64
 1   N_Days         418 non-null    int64
 2   Status         418 non-null    object
 3   Drug           312 non-null    object
 4   Age            418 non-null    int64
 5   Sex            418 non-null    object
 6   Ascites        312 non-null    object
 7   Hepatomegaly   312 non-null    object
 8   Spiders        312 non-null    object
 9   Edema          418 non-null    object
 10  Bilirubin      418 non-null    float64
 11  Cholesterol    284 non-null    float64
 12  Albumin        418 non-null    float64
 13  Copper         310 non-null    float64
 14  Alk_Phos       312 non-null    float64
 15  SGOT           312 non-null    float64
 16  Tryglicerides  282 non-null    float64
 17  Platelets      407 non-null    float64
 18  Prothrombin    416 non-null    float64
 19  Stage          412 non-null    float64
dtypes: float64(10), int64(3), object(7)
memory usage: 65.4+ KB

#### Selecting rows and columns

In [38]:
df_drug = df['Drug']
df_drug.head(10)

0    D-penicillamine
1    D-penicillamine
2    D-penicillamine
3    D-penicillamine
4            Placebo
5            Placebo
6            Placebo
7            Placebo
8    D-penicillamine
9            Placebo
Name: Drug, dtype: object

In [41]:
df_drug.tail(10)

408    NaN
409    NaN
410    NaN
411    NaN
412    NaN
413    NaN
414    NaN
415    NaN
416    NaN
417    NaN
Name: Drug, dtype: object

#### Multiple columns

In [48]:
subset = df[['Drug', 'Age', 'Sex']]
subset.head()

              Drug    Age Sex
0  D-penicillamine  21464   F
1  D-penicillamine  20617   F
2  D-penicillamine  25594   M
3  D-penicillamine  19994   F
4          Placebo  13918   F

In [51]:
subset.shape

(418, 3)

Passing to a list

In [55]:
sub_columns = ['Drug', 'Age', 'Sex']
sub_df = df[sub_columns]
sub_df.head()

              Drug    Age Sex
0  D-penicillamine  21464   F
1  D-penicillamine  20617   F
2  D-penicillamine  25594   M
3  D-penicillamine  19994   F
4          Placebo  13918   F

#### Filtering and aggragation

In [68]:
df.groupby('Sex')['Cholesterol'].mean()

Sex
F    370.502008
M    362.457143
Name: Cholesterol, dtype: float64

In [87]:
df.groupby(['N_Days', 'Sex']) \
[['Cholesterol', 'Age']]. \
mean().head(n=20)

            Cholesterol      Age
N_Days Sex
41     F          175.0  20433.0
43     F            NaN  17897.0
51     F          200.0  25772.0
71     F          394.0  18972.0
77     F          175.0  19884.0
94     F            NaN  16802.0
110    F          188.0  17884.0
111    F            NaN  19724.0
130    F            NaN  16944.0
131    F          178.0  19698.0
140    M          168.0  25340.0
179    F          222.0  25899.0
186    F          260.0  21483.0
191    M          151.0  24803.0
193    F            NaN  18993.0
198    F          345.0  13616.0
207    F            NaN  21247.0
216    F         1092.0  19246.0
221    F            NaN  18628.0
223    F          334.0  22546.0

Flatten out the results

In [91]:
df.groupby(['N_Days', 'Sex']) \
[['Cholesterol', 'Age']]. \
mean(). \
reset_index().\
head(15)

    N_Days Sex  Cholesterol      Age
0       41   F        175.0  20433.0
1       43   F          NaN  17897.0
2       51   F        200.0  25772.0
3       71   F        394.0  18972.0
4       77   F        175.0  19884.0
5       94   F          NaN  16802.0
6      110   F        188.0  17884.0
7      111   F          NaN  19724.0
8      130   F          NaN  16944.0
9      131   F        178.0  19698.0
10     140   M        168.0  25340.0
11     179   F        222.0  25899.0
12     186   F        260.0  21483.0
13     191   M        151.0  24803.0
14     193   F          NaN  18993.0

Count unique

In [97]:
df.groupby('Sex')['Cholesterol'].nunique()

Sex
F    182
M     33
Name: Cholesterol, dtype: int64